"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
    FiSearch,
    FiDownload,
    FiFileText
} from "react-icons/fi";

import { downloadCompanyReport } from "../services/managerService";
import { FiTrash2 } from "react-icons/fi";
import { deleteCompanyReport } from "../services/managerService";
export default function CompanyReportsTable({

    reports = []

}) {

    const [search, setSearch] = useState("");

    const filteredReports = useMemo(() => {

        return reports.filter((report) =>

            report.original_filename
                ?.toLowerCase()
                .includes(search.toLowerCase())

            ||

            String(report.employee_id)
                .includes(search)

        );

    }, [reports, search]);



    const downloadPdf = async (reportId) => {

        try {

            const response = await downloadCompanyReport(reportId);

            const url = window.URL.createObjectURL(

                new Blob([response])

            );

            const link = document.createElement("a");

            link.href = url;

            link.download = `Report_${reportId}.pdf`;

            document.body.appendChild(link);

            link.click();

            link.remove();

            window.URL.revokeObjectURL(url);

        }

        catch (error) {

            console.error(error);

            alert(

                error.response?.data?.detail ||

                "Unable to download report."

            );

        }

    };
    const handleDelete = async (reportId) => {

        const confirmed = window.confirm(
            "Are you sure you want to delete this report?"
        );

        if (!confirmed) return;

        try {

            await deleteCompanyReport(reportId);

            alert("Report deleted successfully.");

            window.location.reload();

        }

        catch (error) {

            console.error(error);

            alert(
                error.response?.data?.detail ||
                "Unable to delete report."
            );

        }

    };


    const getStatusStyle = (status) => {

        switch (status) {

            case "COMPLETED":

                return "bg-green-100 text-green-700";

            case "FAILED":

                return "bg-red-100 text-red-700";

            case "UPLOADING":

            case "TRANSCRIBING":

            case "AI_ANALYZING":

            case "GENERATING_REPORT":

                return "bg-yellow-100 text-yellow-700";

            default:

                return "bg-slate-100 text-slate-700";

        }

    };



    return (

        <div className="overflow-hidden rounded-2xl bg-white shadow-lg">

            {/* Header */}

            <div className="border-b border-slate-200 p-6">

                <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">

                    <div>

                        <h2 className="flex items-center gap-2 text-2xl font-bold text-slate-800">

                            <FiFileText />

                            Company Reports

                        </h2>

                        <p className="mt-2 text-slate-500">

                            View all reports generated by employees.

                        </p>

                    </div>

                    <div className="relative">

                        <FiSearch
                            className="absolute left-3 top-3 text-slate-400"
                        />

                        <input

                            type="text"

                            value={search}

                            onChange={(e) =>
                                setSearch(e.target.value)
                            }

                            placeholder="Search filename or Employee ID..."

                            className="w-80 rounded-xl border border-slate-300 py-2 pl-10 pr-4 outline-none transition focus:border-blue-600"

                        />

                    </div>

                </div>

            </div>



            {/* Table */}

            <div className="overflow-x-auto">

                <table className="min-w-full">

                    <thead className="bg-slate-100">

                        <tr>

                            <th className="px-6 py-4 text-left text-sm font-semibold">

                                Employee ID

                            </th>

                            <th className="px-6 py-4 text-left text-sm font-semibold">

                                Audio File

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Confidence

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Customer

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Agent

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Duration

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Status

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Uploaded

                            </th>

                            <th className="px-6 py-4 text-center text-sm font-semibold">

                                Action

                            </th>

                        </tr>

                    </thead>

                    <tbody>

                        {

                            filteredReports.length === 0 && (

                                <tr>

                                    <td

                                        colSpan={9}

                                        className="py-16 text-center text-slate-500"

                                    >

                                        No reports found.

                                    </td>

                                </tr>

                            )

                        }

                        {

                            filteredReports.map((report) => (

                                <tr

                                    key={report.report_id}

                                    className="border-t border-slate-100 transition hover:bg-slate-50"

                                >

                                    <td className="px-6 py-5 font-semibold text-blue-700">

                                        #{report.employee_id}

                                    </td>

                                    <td className="px-6 py-5">

                                        <div>

                                            <p className="font-medium text-slate-800">

                                                {report.original_filename}

                                            </p>

                                            <p className="text-xs text-slate-500">

                                                Report ID :

                                                {" "}

                                                {report.report_id}

                                            </p>

                                        </div>

                                    </td>

                                    <td className="px-6 py-5 text-center font-bold text-green-600">

                                        {report.confidence_score}

                                    </td>

                                    <td className="px-6 py-5 text-center text-blue-600">

                                        {report.customer_score}

                                    </td>

                                    <td className="px-6 py-5 text-center text-purple-600">

                                        {report.agent_score}

                                    </td>

                                    <td className="px-6 py-5 text-center">

                                        {

                                            Number(

                                                report.call_duration || 0

                                            ).toFixed(1)

                                        }

                                        s

                                    </td>

                                    <td className="px-6 py-5 text-center">

                                        <span

                                            className={`rounded-full px-3 py-1 text-xs font-semibold ${getStatusStyle(report.processing_status)}`}

                                        >

                                            {report.processing_status}

                                        </span>

                                    </td>

                                    <td className="px-6 py-5 text-center text-sm text-slate-500">

                                        {

                                            new Date(

                                                report.created_at

                                            ).toLocaleDateString()

                                        }

                                    </td>

                                    <td className="px-6 py-5">

                                        <div className="flex justify-center gap-2">

                                            <Link
                                                href={`/manager/report/${report.report_id}`}
                                                className="rounded-lg bg-blue-600 px-3 py-2 text-white hover:bg-blue-700"
                                            >
                                                View
                                            </Link>

                                            <button
                                                onClick={() =>
                                                    downloadPdf(report.report_id)
                                                }
                                                className="rounded-lg bg-green-600 p-2 text-white hover:bg-green-700"
                                            >
                                                <FiDownload />
                                            </button>
                                            <button
                                                onClick={() => handleDelete(report.report_id)}
                                                className="rounded-lg bg-red-600 p-2 text-white hover:bg-red-700"
                                            >
                                                <FiTrash2 />
                                            </button>
                                        </div>

                                    </td>

                                </tr>

                            ))

                        }

                    </tbody>

                </table>

            </div>

        </div>

    );

}
